export const resultStatusNoProyect = {
    "progress": -1,
    "toDoSubtasks": -1,
    "inProgressSubtasks": -1,
    "doneSubtasks":-1
};

export const resultGetJiraInfo = {
    data: {
        "expand":"schema,names",
        "startAt":0,
        "maxResults":100,
        "total":3,
        "issues":[
            {"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"10105","self":"https://choiceworx-test.atlassian.net/rest/api/latest/issue/10105","key":"N0D3E6-5","fields":{"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10003","id":"10003","description":"A small piece of work that's part of a larger task.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10316&avatarType=issuetype","name":"Sub-task","subtask":true,"avatarId":10316},"progress":{"progress":0,"total":0},"parent":{"id":"10102","key":"N0D3E6-2","self":"https://choiceworx-test.atlassian.net/rest/api/2/issue/10102","fields":{"summary":"Other steps","status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}},"priority":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/priority/3","iconUrl":"https://choiceworx-test.atlassian.net/images/icons/priorities/medium.svg","name":"Medium","id":"3"},"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10001","id":"10001","description":"Functionality or a feature expressed as a user goal.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype","name":"Story","subtask":false,"avatarId":10315}}},"status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}}}},
            {"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"10104","self":"https://choiceworx-test.atlassian.net/rest/api/latest/issue/10104","key":"N0D3E6-4","fields":{"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10003","id":"10003","description":"A small piece of work that's part of a larger task.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10316&avatarType=issuetype","name":"Sub-task","subtask":true,"avatarId":10316},"progress":{"progress":0,"total":0},"parent":{"id":"10101","key":"N0D3E6-1","self":"https://choiceworx-test.atlassian.net/rest/api/2/issue/10101","fields":{"summary":" JIRASUB1","status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}},"priority":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/priority/3","iconUrl":"https://choiceworx-test.atlassian.net/images/icons/priorities/medium.svg","name":"Medium","id":"3"},"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10001","id":"10001","description":"Functionality or a feature expressed as a user goal.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype","name":"Story","subtask":false,"avatarId":10315}}},"status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}}}},
            {"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"10103","self":"https://choiceworx-test.atlassian.net/rest/api/latest/issue/10103","key":"N0D3E6-3","fields":{"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10003","id":"10003","description":"A small piece of work that's part of a larger task.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10316&avatarType=issuetype","name":"Sub-task","subtask":true,"avatarId":10316},"progress":{"progress":0,"total":0},"parent":{"id":"10102","key":"N0D3E6-2","self":"https://choiceworx-test.atlassian.net/rest/api/2/issue/10102","fields":{"summary":"Other steps","status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}},"priority":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/priority/3","iconUrl":"https://choiceworx-test.atlassian.net/images/icons/priorities/medium.svg","name":"Medium","id":"3"},"issuetype":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/issuetype/10001","id":"10001","description":"Functionality or a feature expressed as a user goal.","iconUrl":"https://choiceworx-test.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype","name":"Story","subtask":false,"avatarId":10315}}},"status":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/status/10003","description":"","iconUrl":"https://choiceworx-test.atlassian.net/","name":"To Do","id":"10003","statusCategory":{"self":"https://choiceworx-test.atlassian.net/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}}}}
        ]
    }
};

export const resultStatusProyect = {
    "progress": 0,
    "toDoSubtasks": 3,
    "inProgressSubtasks": 0,
    "doneSubtasks": 0
};